### ISSUE TITLE
Installation error 500

### ISSUE THREAD

**Issue by facetheheat** [AlexxIT/FasterWhisper#1]
Setup:
- latest HA in docker `docker pull homeassistant/home-assistant:latest`, 
- trying to setup FasterWhisper: Settings > Integrations > Add Integration > Faster Whisper
- Error pop up message:

<img width="437" alt="Screenshot 2023-05-30 at 14 58 37" src="https://github.com/AlexxIT/FasterWhisper/assets/1582399/c6087043-edd2-4f28-9b3c-67ba6516ea74">

System Logs:
```
Logger: aiohttp.server
Source: requirements.py:290 
First occurred: 2:57:55 PM (1 occurrences) 
Last logged: 2:57:55 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 863, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 962, in async_create_flow
    await _load_integration(self.hass, handler_key, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2026, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 389, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 290, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for faster_whisper not found: ['wyoming-faster-whisper==0.0.3'].
```

Trying to force setup in HA docker container:
```
- $ docker exec -it the_homeassistant /bin/bash
- # uname -a
Linux the_homeassistant 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 Linux
- the_homeassistant:/config# python3 -m pip install wyoming-faster-whisper==0.0.3
Collecting wyoming-faster-whisper==0.0.3
  Using cached wyoming_faster_whisper-0.0.3.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wyoming==0.0.1 in /usr/local/lib/python3.10/site-packages (from wyoming-faster-whisper==0.0.3) (0.0.1)
INFO: pip is looking at multiple versions of wyoming-faster-whisper to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement ctranslate2<4,>=3.5 (from wyoming-faster-whisper) (from versions: none)
ERROR: No matching distribution found for ctranslate2<4,>=3.5

```

**Comment by subivoodoo** [comment]
Same issue here...

**Comment by eyal1izhaki** [comment]
Here too

**Comment by smolowik** [comment]
same error :(

**Comment by Shiroe93** [comment]
Same here

**Comment by lraty** [comment]
Same here. Any solution?

**Comment by Shiroe93** [comment]
The official add on has been updated to faster whisper so I think there's no need for this one

**Comment by zephirus** [comment]
Same error. @Shiroe93 what do you mean?

**Comment by grrrva** [comment]
Hello, same here with 
--
ERRATA CORRIGE: 

Linux myhost 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux


Thanks!

**Comment by ICULikeMac** [comment]
Same issue here too. Ubuntu 22.04 -> Docker -> HA -> Custom component.

**Comment by AlexxIT** [comment]
Should be fixed in latest update

**Comment by facetheheat** [comment]
Maybe requirements should be 1.1.0 instead of 1.0.1?
>https://github.com/rhasspy/wyoming-faster-whisper/tags

```
Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 13:10:16 (3 occurrences)
Last logged: 13:10:32

Unable to install package wyoming-faster-whisper==1.0.1: ERROR: Could not find a version that satisfies the requirement ctranslate2<4,>=3.17 (from wyoming-faster-whisper) (from versions: none) ERROR: No matching distribution found for ctranslate2<4,>=3.17
Unable to install package wyoming-faster-whisper==1.0.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f23a55ecad0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/wyoming-faster-whisper/ ERROR: Could not find a version that satisfies the requirement ctranslate2<4,>=3.17 (from wyoming-faster-whisper) (from versions: none) ERROR: No matching distribution found for ctranslate2<4,>=3.17
```

**Comment by AlexxIT** [comment]
No. Current version 1.0.1
https://github.com/home-assistant/addons/blob/2a8452b5c9ffd08dc8cedf052249c861d1e6d35d/whisper/build.yaml#L9

I don't have any problems on Windows. Will check Linux.

**Comment by grrrva** [comment]
Hello, 
my issue is related for sure with ctranslate2 library and the arm cpu architecture of the raspberry. 
I have issues to install ctranslate2 even outside HA, I compiled the cpp library but failing to compile the python wrapper.

link of error here: https://forum.opennmt.net/t/ctranslate2-errors-in-compiling-python-wrapper-on-raspberry-pi-4-implicit-narrowing-is-not-permitted/5636

Thanks

**Comment by AlexxIT** [comment]
ctranslate2 should have wheels for x86_64 and for aarch64. Are you install 32bit ARM OS?

https://pypi.org/simple/ctranslate2/

**Comment by grrrva** [comment]
> ctranslate2 should have wheels for x86_64 and for aarch64. Are you install 32bit ARM OS?
> 
> https://pypi.org/simple/ctranslate2/

I'll give a look at that. 

my uname -a output is: 

Linux myhost 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux

so I guess I am on 64 bit OS. 

thank you

**Comment by AlexxIT** [comment]
Looks like common linux wheels (`manylinux`) not compatible with Hass wheels (`musllinux`), because Hass docker images based on Alpine linux. This is BIG problem. I thinks it can't be solved with easy way.

**Comment by pjuhl2313** [comment]
Logger: homeassistant.util.package
Source: util/package.py:122
First occurred: 11:34:07 PM (3 occurrences)
Last logged: 11:34:13 PM

Unable to install package wyoming-faster-whisper==1.0.1: ERROR: Could not find a version that satisfies the requirement ctranslate2<4,>=3.17 (from wyoming-faster-whisper) (from versions: none) ERROR: No matching distribution found for ctranslate2<4,>=3.17

This is the error I get when trying to install on HA. My HA is in a VM on an unRaid server.

**Comment by grrrva** [comment]
Hello,
I solved, it was because my Raspberry OS was 32 bit.
I reinstalled with 64 bit version and everything worked fine.

Check if your system (the O.S., not the CPU) is 32 bit.



Il giorno mar 27 feb 2024 alle ore 05:36 pjuhl2313 ***@***.***>
ha scritto:

**Comment by AlexxIT** [comment]
This component doesn't support:
- Hass docker (linux x86)

This component can be used with (64 bit):
- HassWP (windows)
- Hass venv (linux x86, linux arm)
- Hass docker (linux arm)

**Comment by Stephan-4711** [comment]
I'm using HAOS in a VM x64 and I also get the error 500

**Comment by Xornop** [comment]
I am also getting the error, on a 64 bit NUC with HAOS
Great to see that this bug report exists since May last year and hasn't been fixed - must be a hard one.

**Comment by matze19999** [comment]
Same problem here, also NUC x86 with HAOS.

**Comment by mikhakhaldea** [comment]
Same problem HA on docker x86 with HAOS. ubuntu 22.04

**Comment by ItamarCoh3n** [comment]
same problem with HA docker, linux x64

**Comment by skom27** [comment]
I have the same problem
System: Linux Wyse 5.10.0-33-amd64 #1 SMP Debian 5.10.226-1 (2024-10-03) x86_64 GNU/Linux
Logs:
Unable to install package wyoming-faster-whisper==1.0.1: × No solution found when resolving dependencies: ╰─▶ Because only the following versions of ctranslate2 are available: ctranslate2<=3.17.0 ctranslate2==3.17.1 ctranslate2= =3.18.0 ctranslate2==3.19.0 ctranslate2==3.20.0 ctranslate2==3.21.0 ctranslate2==3.22.0 ctranslate2==3.23.0 ctranslate2==3.24.0 ctranslate2>4 and ctranslate2>=3.17.0,<=3.24.0 has no wheels with a matching Python ABI tag, we can conclude that ctranslate2>=3.17.0,<3.17.1 cannot be used. And because wyoming-faster-whisper==1.0.1 depends on ctranslate2>=3.17,<4 and you require wyoming-faster-whisper==1.0.1, we can conclude that your requirements are unsatisfiable.

**Comment by ZodWindsong** [comment]
Hi, 
Am having the same problem:

Is there a fix yet?
Is there any way to get this working\installed on HA?
```
--------Error message quoted below--------
Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 6:59:50 PM (3 occurrences)
Last logged: 6:59:53 PM

Unable to install package wyoming-faster-whisper==1.0.1: × No solution found when resolving dependencies: ╰─▶ Because only the following versions of ctranslate2 are available: ctranslate2<=3.17.0 ctranslate2==3.17.1 ctranslate2==3.18.0 ctranslate2==3.19.0 ctranslate2==3.20.0 ctranslate2==3.21.0 ctranslate2==3.22.0 ctranslate2==3.23.0 ctranslate2==3.24.0 ctranslate2>4 and ctranslate2>=3.17.0,<=3.24.0 has no wheels with a matching Python ABI tag, we can conclude that ctranslate2>=3.17.0,<3.17.1 cannot be used. And because wyoming-faster-whisper==1.0.1 depends on ctranslate2>=3.17,<4 and you require wyoming-faster-whisper==1.0.1, we can conclude that your requirements are unsatisfiable.
-----------
```
System info:
64 bit Ubuntu Linux (latest) on x86
Virtualbox running Home assistant

**Comment by Hogobarth1** [comment]
Oh, a fix would be very nice, I also have this problem: OMV, Debian GNU/Linux 12 (bookworm) 6.1.0-30-amd64
Hope you find the time :)

**Comment by pos-ei-don** [comment]
Same here

**Comment by oepoemoepoe** [comment]
> Hi, Am having the same problem:
> 
> Is there a fix yet? Is there any way to get this working\installed on HA?
> 
> ```
> --------Error message quoted below--------
> Logger: homeassistant.util.package
> Source: util/package.py:152
> First occurred: 6:59:50 PM (3 occurrences)
> Last logged: 6:59:53 PM
> 
> Unable to install package wyoming-faster-whisper==1.0.1: × No solution found when resolving dependencies: ╰─▶ Because only the following versions of ctranslate2 are available: ctranslate2<=3.17.0 ctranslate2==3.17.1 ctranslate2==3.18.0 ctranslate2==3.19.0 ctranslate2==3.20.0 ctranslate2==3.21.0 ctranslate2==3.22.0 ctranslate2==3.23.0 ctranslate2==3.24.0 ctranslate2>4 and ctranslate2>=3.17.0,<=3.24.0 has no wheels with a matching Python ABI tag, we can conclude that ctranslate2>=3.17.0,<3.17.1 cannot be used. And because wyoming-faster-whisper==1.0.1 depends on ctranslate2>=3.17,<4 and you require wyoming-faster-whisper==1.0.1, we can conclude that your requirements are unsatisfiable.
> -----------
> ```
> 
> System info: 64 bit Ubuntu Linux (latest) on x86 Virtualbox running Home assistant

I have the same exact error on 64-bit ARM.

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by JAMMS247** [comment]
Same issue here on a Docker Linux install. Please fix!

**Comment by ange007** [comment]
Any news?
How can fix this?
HASS and Faster-Whisper install from Docker.

**Comment by Hatzen** [comment]
Same for asahi linux on a mac studio max with podman

current logs
```
2025-08-20 22:10:13.995 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.2.xxx
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 188, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 83, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1446, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1482, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1704, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.hass, handler_key, self._hass_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3779, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3756, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 584, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
        hass, integration.domain
    )
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
        integration.domain, integration.requirements
    )
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 264, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 292, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for faster_whisper not found: ['wyoming-faster-whisper==1.0.1'].
```

local installtion show it fails for unavailable packages
```
sir-macstudio:/config# python3 -m pip install wyoming-faster-whisper==1.0.1 Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/ Collecting wyoming-faster-whisper==1.0.1 Downloading wyoming_faster_whisper-1.0.1.tar.gz (11 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting wyoming==1.1.0 (from wyoming-faster-whisper==1.0.1) Downloading https://wheels.home-assistant.io/musllinux-index/wyoming-1.1.0-py3-none-any.whl.metadata (636 bytes) INFO: pip is looking at multiple versions of wyoming-faster-whisper to determine which version is compatible with other requirements. This could take a while. ERROR: Could not find a version that satisfies the requirement ctranslate2<4,>=3.17 (from wyoming-faster-whisper) (from versions: none) ERROR: No matching distribution found for ctranslate2<4,>=3.17
```
Which is weird as there is support since 
https://github.com/OpenNMT/CTranslate2/releases/tag/v2.16.0

**Comment by AlexxIT** [comment]
So. Three years later, I finally solved this problem:
https://github.com/AlexxIT/FasterWhisper/releases/tag/v2.0.0

Compiling CTranslate2 for musl was a real challenge. It must be noted that practically all modern ASR projects do not work in Alpine.
