### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by StefanoGiu** [AlexxIT/FasterWhisper#3]
Config:
Model: tiny or tiny-int8
Language: it
Beam size: 5
CPU Threads: 0

```
2023-09-12 19:26:07.426 WARNING (SyncWorker_0) [wyoming_faster_whisper.download] Model hashes do not match
2023-09-12 19:26:07.427 WARNING (SyncWorker_0) [wyoming_faster_whisper.download] Expected: {'config.json': 'e5a2f85afc17f73960204cad2b002633', 'model.bin': 'c21f8eccfdc11978e9496dcb731c54e2', 'vocabulary.txt': 'c1120a13c94a8cbb132489655cdd1854'}
2023-09-12 19:26:07.427 WARNING (SyncWorker_0) [wyoming_faster_whisper.download] Got: {'model.bin': '', 'config.json': '', 'vocabulary.txt': ''}
2023-09-12 19:26:07.691 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "XXX\Python\Python311\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\http\security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\http\forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\http\request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\http\ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\http\auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\http\view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\config\config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\components\http\data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\helpers\data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\data_entry_flow.py", line 296, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\site-packages\homeassistant\data_entry_flow.py", line 392, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "YYY\.homeassistant\custom_components\faster_whisper\config_flow.py", line 28, in async_step_user
    ok = await self.hass.loop.run_in_executor(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "YYY\.homeassistant\custom_components\faster_whisper\config_flow.py", line 22, in find_or_download_model
    return download_model(model, model_path) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "YYY\.homeassistant\deps\Python311\site-packages\wyoming_faster_whisper\download.py", line 90, in download_model
    with urlopen(model_url) as response:
         ^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "XXX\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by StefanoGiu** [comment]
The generated URL is wrong:
https://github.com/rhasspy/models/releases/download/v1.0/asr_faster-whisper-FasterWhisperModel.TINY_INT8.tar.gz
instead of
https://github.com/rhasspy/models/releases/download/v1.0/asr_faster-whisper-TINY-INT8.tar.gz

**Comment by StefanoGiu** [comment]
I fixed it changing the line
  model_url = URL_FORMAT.format(model=model)
to:
  model_url = URL_FORMAT.format(model=model.value)
in the wyoming_faster_whisper\download.py.

Now Faster Whisper is installed, but I cannot see it under vocal assistants when I add a new assistant...

**Comment by StefanoGiu** [comment]
I have this error:
```
2023-09-13 08:28:20.546 ERROR (MainThread) [homeassistant.components.stt] Error while setting up faster_whisper platform for stt
Traceback (most recent call last):
  File "YYYPython311\Lib\site-packages\homeassistant\helpers\entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "XXX.homeassistant\custom_components\faster_whisper\stt.py", line 21, in async_setup_entry
    async_add_entities([FasterWhisperSTT(hass, config_entry)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX.homeassistant\custom_components\faster_whisper\stt.py", line 28, in __init__
    self.model = WhisperModel(
                 ^^^^^^^^^^^^^
  File "XXX.homeassistant\deps\Python311\site-packages\wyoming_faster_whisper\faster_whisper\transcribe.py", line 69, in __init__
    self.ids_to_tokens = [line.rstrip("\n") for line in vocab_file]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX.homeassistant\deps\Python311\site-packages\wyoming_faster_whisper\faster_whisper\transcribe.py", line 69, in <listcomp>
    self.ids_to_tokens = [line.rstrip("\n") for line in vocab_file]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "YYYPython311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 282: character maps to <undefined>
```

**Comment by StefanoGiu** [comment]
I fixed the above error forcing UTF8 encoding in the file:
XXX\.homeassistant\deps\Python311\site-packages\wyoming_faster_whisper\faster_whisper\transcribe.py

With the following line:
with open(os.path.join(model_path, "vocabulary.txt"), encoding="utf8") as vocab_file:

**Comment by StefanoGiu** [comment]
Now FasterWhisper seems to work properly...

**Comment by Thoranius42** [comment]
Hello,
I have the same problem but changing the model_url line in download.py as you suggested didn't help. Here is my error log. Do you know what to do to fix this?
Thx for your help

Update: Ok nevermind, I just had to restart HA and it was working properly as you said.

```
Logger: aiohttp.server
Source: custom_components/faster_whisper/config_flow.py:22
Integration: Faster Whisper (documentation, issues)
First occurred: 07:28:13 (8 occurrences)
Last logged: 07:41:21

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/data_entry_flow.py", line 298, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/homeassistant-config/.homeassistant/custom_components/faster_whisper/config_flow.py", line 28, in async_step_user
    ok = await self.hass.loop.run_in_executor(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/homeassistant-config/.homeassistant/custom_components/faster_whisper/config_flow.py", line 22, in find_or_download_model
    return download_model(model, model_path) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/wyoming_faster_whisper/download.py", line 90, in download_model
    with urlopen(model_url) as response:
         ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by AlexxIT** [comment]
I have tested latest version. Can't confirm issue. Please reopen the issue if there are still any problems
