### ISSUE TITLE
wyoming_faster_whisper - Detected blocking call to open

### ISSUE THREAD

**Issue by StefanoGiu** [AlexxIT/FasterWhisper#5]
Starting from the upgrade to Home Assistant 2024.6.3 I got this

```
2024-06-25 15:29:56.417 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('XXX.homeassistant\faster_whisper\tiny-int8\vocabulary.txt',) in XXX.homeassistant\deps\Python312\site-packages\wyoming_faster_whisper\faster_whisper\transcribe.py, line 68: with open(os.path.join(model_path, "vocabulary.txt"), encoding="utf8") as vocab_file: inside the event loop
Traceback (most recent call last):
File "", line 198, in run_module_as_main
File "", line 88, in run_code
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant_main.py", line 223, in
sys.exit(main())
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant_main.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "ZZZ\Python\Python312\Lib\asyncio\base_events.py", line 672, in run_until_complete
self.run_forever()
File "ZZZ\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "ZZZ\Python\Python312\Lib\asyncio\base_events.py", line 639, in run_forever
self._run_once()
File "ZZZ\Python\Python312\Lib\asyncio\base_events.py", line 1985, in _run_once
handle._run()
File "ZZZ\Python\Python312\Lib\asyncio\events.py", line 88, in _run
self._context.run(self.callback, *self.args)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\config_entries.py", line 742, in async_setup_locked
await self.async_setup(hass, integration=integration)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "XXX.homeassistant\custom_components\faster_whisper_init.py", line 11, in async_setup_entry
await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\config_entries.py", line 2032, in async_forward_entry_setups
await asyncio.gather(
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\config_entries.py", line 2034, in
create_eager_task(
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\util\async.py", line 37, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\config_entries.py", line 2081, in async_forward_entry_setup
await entry.async_setup(self.hass, integration=integration)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\components\stt_init.py", line 145, in async_setup_entry
return await component.async_setup_entry(entry)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\helpers\entity_component.py", line 196, in async_setup_entry
return await self._platforms[key].async_setup_entry(config_entry)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\helpers\entity_platform.py", line 333, in async_setup_entry
return await self._async_setup_platform(async_create_setup_awaitable)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\helpers\entity_platform.py", line 363, in async_setup_platform
awaitable = create_eager_task(awaitable, loop=hass.loop)
File "ZZZ\Python\Python312\Lib\site-packages\homeassistant\util\async.py", line 37, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "XXX.homeassistant\custom_components\faster_whisper\stt.py", line 21, in async_setup_entry
async_add_entities([FasterWhisperSTT(hass, config_entry)])
File "XXX.homeassistant\custom_components\faster_whisper\stt.py", line 28, in init
self.model = WhisperModel(
File "XXX.homeassistant\deps\Python312\site-packages\wyoming_faster_whisper\faster_whisper\transcribe.py", line 68, in init
with open(os.path.join(model_path, "vocabulary.txt"), encoding="utf8") as vocab_file:
```
It was working on 2024.4.0

**Comment by AlexxIT** [comment]
This is probably no longer relevant
https://github.com/AlexxIT/FasterWhisper/releases/tag/v2.0.0
